namespace QLFILM.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddDataIntoActors : DbMigration
    {
        public override void Up()
        {
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A001', N'Van Hong');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A002', N'Bich Phuong Huynh');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A003', N'Lan Huong Nguyen');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A004', N'Hoai Nam Vo');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A005', N'Lam Thanh My');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A006', N'Lap Huynh');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A007', N'Truong huu Quy');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A008', N'The Vinh Truong');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A009', N'Tran Thi Nha Phuong');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A010', N'Kim Ly');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A011', N'Mac Van Khoa');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A012', N'Linh Hoài');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A013', N'Charlie Nguyen');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A014', N'Vi Tu');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A015', N'Son Bao Tran');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A016', N'Vu T. Le Thi');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A017', N'Huy Khanh');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A018', N'Phuong Minh');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A019', N'Khuong Ngoc');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A020', N'Thu Trang');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A021', N'Ha Hien');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A022', N'B Tran');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A023', N'Le Chi Kien');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A024', N'Doan Duong');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A025', N'Kaity Nguyen');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A026', N'Thanh Nhien Phan');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A027', N'Nga Thúy');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A028', N'Ha Phong Nguyen');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A029', N'Quy Binh');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A030', N'Chi Bao');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A031', N'Takafumi Akutsu');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A032', N'Cao De Hoang');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A033', N'Luu Duc');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A034', N'Jun Pham');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A035', N'Minh Huong');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A036', N'Kathy Uyen');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A037', N'Maurice Nash');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A038', N'Anh Hieu');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A039', N'Mathew M. Korsch');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A040', N'Phu Cuong Lai');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A041', N'Thanh Duy');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A042', N'Leon Le');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A043', N'Ngoc Bao Ta');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A044', N'Phuong Bella');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A045', N'Tuc Cuong');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A046', N'Noriko Takimoto');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A047', N'Pham Quynh Anh');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A048', N'Hoa Mai');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A049', N'Ngoc Anh Vu');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A050', N'Huy Hoang');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A051', N'Kathleen Luong');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A052', N'Hoang Tran Minh Duc');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A053', N'Hieu Hien');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A054', N'Mi Du');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A055', N'Ngoc Hung Dao');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A056', N'To Tuan Dang');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A057', N'Thai Hoa');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A058', N'Bich Ngoc Nguyen');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A059', N'Minh Hang');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A060', N'Cat Ly');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A061', N'Long Dien');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A062', N'Dinh Y Nhung');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A063', N'Kim Chi');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A064', N'Trúc Anh');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A065', N'Midu');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A066', N'Quang Vinh Luu');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A067', N'Phuong Anh Leu');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A068', N'Ngoc Diep');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A069', N'Linh Dan Pham');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A070', N'Zan Sram Kra');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A071', N'Anh Hong');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A072', N'Tina Duong');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A073', N'Lâm Vissay');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A074', N'Van Hai Bui');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A075', N'Huynh Anh Lê');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A076', N'Van Trang');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A077', N'Vinh Khoa Ho');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A078', N'Khanh Van');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A079', N'Nguyen Trung Dan');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A080', N'Kris Duangphung');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A081', N'Michael Jarmus');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A082', N'Thanh Tu Nguyen');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A083', N'Kim Xuan');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A084', N'Elly Tran');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A085', N'Kim Long Thach');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A086', N'Nhu Quynh Nguyen');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A087', N'Tran Nghia');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A088', N'Yen Hoang');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A089', N'Nguyen Thai An');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A090', N'Trung Kien Nguyen');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A091', N'Nguyen Hau');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A092', N'Ngan Thai');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A093', N'Mai Cát Vi');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A094', N'Thuy Hoa');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A095', N'Hoang Ha');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A096', N'Cong Ninh Nguyen');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A097', N'Yu Duong');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A098', N'Phuong-Thanh');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A099', N'Vo Dien Gia Huy');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A100', N'Le Huynh');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A101', N'Binh An');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A102', N'Kha Ngan');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A103', N'Ba Loc Duong');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A104', N'Bich Ngoc');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A105', N'Minh Thuan');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A106', N'Huynh Dong');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A107', N'Jayvee Mai The Hiep');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A108', N'Hong Dao');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A109', N'Ngo The Quan');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A110', N'Thien Tu Tran');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A111', N'Van Thom Lê');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A112', N'Thi Huong Thao Le');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A113', N'Khanh Le');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A114', N'David Tran');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A115', N'Trung Dung');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A116', N'Loc Thanh');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A117', N'Nam Em');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A118', N'Thi Kieu Trinh Nguyen');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A119', N'Le Ha Anh');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A120', N'Le Duy Hai');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A121', N'Tien Luat');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A122', N'Thinh Vinh');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A123', N'Tran Thanh');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A124', N'Phi Phung');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A125', N'Phuong Anh Dao');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A126', N'Hanh Thuy Ngo Pham');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A127', N'Ngoc Thanh Tam');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A128', N'Lam Minh Thang');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A129', N'My Tam');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A130', N'Chi Pu');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A131', N'Do Trong Tan');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A132', N'Diem Lien');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A133', N'Tuan Khai');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A134', N'Phat Trieu Hoang');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A135', N'Vân Lê');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A136', N'Pho Dac Biet');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A137', N'Phuong Mai');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A138', N'Ngoc Phuong Mai');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A139', N'Hanh Tuyet');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A140', N'Khuong Be');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A141', N'Trish Le');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A142', N'Trang Thu');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A143', N'Thang Nguyen');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A144', N'Thuy An Nguyen');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A145', N'Bao Quyen Tang');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A146', N'Trinh Xuan Nhan');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A147', N'Hâu Nguyen Duy');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A148', N'Thanh Minh Phan');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A149', N'Lan Kim');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A150', N'The Lu Le');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A151', N'Hong Phuoc Pham');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A152', N'Johnny Van Tran');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A153', N'Huu Thanh Nguyen');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A154', N'Nguyen Thuy Anh');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A155', N'Thi Ha');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A156', N'Ta Am');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A157', N'Phan Tan Thi');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A158', N'Duy Khoa Nguyen');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A159', N'Thi Hai Yen Do');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A160', N'Long Nguyen');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A161', N'Singer Doan Trang');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A162', N'Cong Hoang Le');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A163', N'Tran Minh Thanh');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A164', N'Veronica Ngo');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A165', N'Maya');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A166', N'Johnny Nguyen');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A167', N'Trinh Ho Khanh');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A168', N'Hong Chuong Nguyen');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A169', N'Trong Hai');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A170', N'Mai Tai Phen');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A171', N'Duc Khue');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A172', N'Le Dung Nhi');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A173', N'Hai Trieu');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A174', N'Hoang Bach');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A175', N'Quynh Hoa');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A176', N'Quang Hai Ngo');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A177', N'Nhung Trang');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A178', N'Ngo Kien Huy');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A179', N'Man San Lu');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A180', N'Chi Bao Pham');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A181', N'Quoc Trung Do');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A182', N'Diem My');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A183', N'De Xuan');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A184', N'Lanh Thanh');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A185', N'Nu Yên-Khê Tran');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A186', N'Hoang Yen Chibi');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A187', N'Truc Diem');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A188', N'Vi Van Hua');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A189', N'Son Bac');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A190', N'Dave Hope');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A191', N'Duong Don');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A192', N'Pham Anh Khoa');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A193', N'Xuan Kim');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A194', N'Nsut Le Thien');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A195', N'Do An');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A196', N'Jackie');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A197', N'Kim Hien');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A198', N'Thu Thuy Pham');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A199', N'Tang Thanh Ha');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A200', N'Truong Ngoc Anh');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A201', N'Manh Hai Luong');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A202', N'Mai Van Thinh');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A203', N'Dustin Nguyen');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A204', N'Anh Hoa Nguyen');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A205', N'My Anh');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A206', N'Binh Minh');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A207', N'Harry Lu');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A208', N'Khanh Quoc Nguyen');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A209', N'Thái Ho');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A210', N'Ninh Duong Lan Ngoc');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A211', N'Thanh Hang');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A212', N'Lan Khue');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A213', N'Chau Bui');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A214', N'Ngoc Minh');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A215', N'Huu Chau');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A216', N'Ngan Khanh');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A217', N'Kieu Minh Tuan');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A218', N'Ngoc Duong Yen');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A219', N'Thu Trang Nguyen');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A220', N'Anh The');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A221', N'Han Thi Pham');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A222', N'Anh Tu');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A223', N'Le Van Loc');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A224', N'Nguyen manh Thang');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A225', N'Tuan Kiet');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A226', N'Linh Son Nguyen');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A227', N'Thi Loc Truong');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A228', N'Cuong Bui');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A229', N'Long Le Vu');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A230', N'My Uyen Dang Tran');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A231', N'Chi Hong');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A232', N'Tran Phong');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A233', N'Quach Ngoc Ngoan');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A234', N'Ha Quoc Hoang');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A235', N'Hoai Phong Duong');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A236', N'Kieu Chinh');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A237', N'Isaac');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A238', N'Chi Tai');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A239', N'Ngoc Hiep Nguyen');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A240', N'Tu Thanh');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A241', N'Bao Anh');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A242', N'Diem Kieu');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A243', N'Hoang Phuc Nguyen');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A244', N'Tat Binh Dang');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A245', N'Bài Bình Bùi');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A246', N'Catherine Ai');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A247', N'Ngoc Quyen');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A248', N'Gary Daniels');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A249', N'Thanh Hien');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A250', N'Thu Diep');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A251', N'Tony Chiu-Wai Leung');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A252', N'Cory Jackson');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A253', N'Minh Khang');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A254', N'Trang Minh');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A255', N'Luu Viet Bao Dang');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A256', N'Hoàng Oanh');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A257', N'Viet Son Le');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A258', N'Le Chi Kein');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A259', N'Tran Le Thuy Vy');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A260', N'Bao Chi');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A261', N'Khang Trong');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A262', N'Alex');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A263', N'Hanh Tran');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A264', N'Dieu Nhi');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A265', N'Toi Lam');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A266', N'Cuong Seven');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A267', N'Bao Son Doan');");
            Sql("INSERT INTO Actors (AID, ActorName) VALUES (N'A268', N'Mang Long Dao');");
        }
        
        public override void Down()
        {
        }
    }
}
